// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace VFXEditor.Flatbuffer.Ephb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EphbBeta : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EphbBeta GetRootAsEphbBeta(ByteBuffer _bb) { return GetRootAsEphbBeta(_bb, new EphbBeta()); }
  public static EphbBeta GetRootAsEphbBeta(ByteBuffer _bb, EphbBeta obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbBeta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public VFXEditor.Flatbuffer.Ephb.EphbGamma? Gamma(int j) { int o = __p.__offset(4); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbGamma?)(new VFXEditor.Flatbuffer.Ephb.EphbGamma()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GammaLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta> CreateEphbBeta(FlatBufferBuilder builder,
      VectorOffset gammaOffset = default(VectorOffset)) {
    builder.StartTable(1);
    EphbBeta.AddGamma(builder, gammaOffset);
    return EphbBeta.EndEphbBeta(builder);
  }

  public static void StartEphbBeta(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddGamma(FlatBufferBuilder builder, VectorOffset gammaOffset) { builder.AddOffset(0, gammaOffset.Value, 0); }
  public static VectorOffset CreateGammaVector(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGammaVectorBlock(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGammaVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGammaVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartGammaVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta> EndEphbBeta(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>(o);
  }
}


static public class EphbBetaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Gamma*/, VFXEditor.Flatbuffer.Ephb.EphbGammaVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
