// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace VFXEditor.Flatbuffer.Ephb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EphbUnknownT : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EphbUnknownT GetRootAsEphbUnknownT(ByteBuffer _bb) { return GetRootAsEphbUnknownT(_bb, new EphbUnknownT()); }
  public static EphbUnknownT GetRootAsEphbUnknownT(ByteBuffer _bb, EphbUnknownT obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbUnknownT __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartEphbUnknownT(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> EndEphbUnknownT(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>(o);
  }
}


static public class EphbUnknownTVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
