// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace VFXEditor.Flatbuffer.Ephb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EphbEpsilon : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EphbEpsilon GetRootAsEphbEpsilon(ByteBuffer _bb) { return GetRootAsEphbEpsilon(_bb, new EphbEpsilon()); }
  public static EphbEpsilon GetRootAsEphbEpsilon(ByteBuffer _bb, EphbEpsilon obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbEpsilon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Unknown1 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown2 { get { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ushort Unknown3 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public float Unknown4 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Unknown5 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon> CreateEphbEpsilon(FlatBufferBuilder builder,
      ushort unknown1 = 0,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      ushort unknown3 = 0,
      float unknown4 = 0.0f,
      float unknown5 = 0.0f) {
    builder.StartTable(5);
    EphbEpsilon.AddUnknown5(builder, unknown5);
    EphbEpsilon.AddUnknown4(builder, unknown4);
    EphbEpsilon.AddUnknown2(builder, unknown2Offset);
    EphbEpsilon.AddUnknown3(builder, unknown3);
    EphbEpsilon.AddUnknown1(builder, unknown1);
    return EphbEpsilon.EndEphbEpsilon(builder);
  }

  public static void StartEphbEpsilon(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddUnknown1(FlatBufferBuilder builder, ushort unknown1) { builder.AddUshort(0, unknown1, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset) { builder.AddOffset(1, unknown2Offset.Value, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, ushort unknown3) { builder.AddUshort(2, unknown3, 0); }
  public static void AddUnknown4(FlatBufferBuilder builder, float unknown4) { builder.AddFloat(3, unknown4, 0.0f); }
  public static void AddUnknown5(FlatBufferBuilder builder, float unknown5) { builder.AddFloat(4, unknown5, 0.0f); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon> EndEphbEpsilon(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>(o);
  }
}


static public class EphbEpsilonVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unknown1*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTable(tablePos, 6 /*Unknown2*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*Unknown3*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*Unknown4*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Unknown5*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
