// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace VFXEditor.Flatbuffer.Ephb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EphbDelta : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbDelta GetRootAsEphbDelta(ByteBuffer _bb) { return GetRootAsEphbDelta(_bb, new EphbDelta()); }
  public static EphbDelta GetRootAsEphbDelta(ByteBuffer _bb, EphbDelta obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbDelta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown1 { get { int o = __p.__offset(4); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown2 { get { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public float Unknown3 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta> CreateEphbDelta(FlatBufferBuilder builder,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      float unknown3 = 0.0f) {
    builder.StartTable(3);
    EphbDelta.AddUnknown3(builder, unknown3);
    EphbDelta.AddUnknown2(builder, unknown2Offset);
    EphbDelta.AddUnknown1(builder, unknown1Offset);
    return EphbDelta.EndEphbDelta(builder);
  }

  public static void StartEphbDelta(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddUnknown1(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset) { builder.AddOffset(0, unknown1Offset.Value, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset) { builder.AddOffset(1, unknown2Offset.Value, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, float unknown3) { builder.AddFloat(2, unknown3, 0.0f); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta> EndEphbDelta(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta>(o);
  }
  public EphbDeltaT UnPack() {
    var _o = new EphbDeltaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbDeltaT _o) {
    _o.Unknown1 = this.Unknown1.HasValue ? this.Unknown1.Value.UnPack() : null;
    _o.Unknown2 = this.Unknown2.HasValue ? this.Unknown2.Value.UnPack() : null;
    _o.Unknown3 = this.Unknown3;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta> Pack(FlatBufferBuilder builder, EphbDeltaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta>);
    var _unknown1 = _o.Unknown1 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown1);
    var _unknown2 = _o.Unknown2 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown2);
    return CreateEphbDelta(
      builder,
      _unknown1,
      _unknown2,
      _o.Unknown3);
  }
}

public class EphbDeltaT
{
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown1 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown2 { get; set; }
  public float Unknown3 { get; set; }

  public EphbDeltaT() {
    this.Unknown1 = null;
    this.Unknown2 = null;
    this.Unknown3 = 0.0f;
  }
}


static public class EphbDeltaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Unknown1*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 6 /*Unknown2*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*Unknown3*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbTheta : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbTheta GetRootAsEphbTheta(ByteBuffer _bb) { return GetRootAsEphbTheta(_bb, new EphbTheta()); }
  public static EphbTheta GetRootAsEphbTheta(ByteBuffer _bb, EphbTheta obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbTheta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Unknown1 { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public float Unknown2 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta> CreateEphbTheta(FlatBufferBuilder builder,
      bool unknown1 = false,
      float unknown2 = 0.0f) {
    builder.StartTable(2);
    EphbTheta.AddUnknown2(builder, unknown2);
    EphbTheta.AddUnknown1(builder, unknown1);
    return EphbTheta.EndEphbTheta(builder);
  }

  public static void StartEphbTheta(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUnknown1(FlatBufferBuilder builder, bool unknown1) { builder.AddBool(0, unknown1, false); }
  public static void AddUnknown2(FlatBufferBuilder builder, float unknown2) { builder.AddFloat(1, unknown2, 0.0f); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta> EndEphbTheta(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta>(o);
  }
  public EphbThetaT UnPack() {
    var _o = new EphbThetaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbThetaT _o) {
    _o.Unknown1 = this.Unknown1;
    _o.Unknown2 = this.Unknown2;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta> Pack(FlatBufferBuilder builder, EphbThetaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta>);
    return CreateEphbTheta(
      builder,
      _o.Unknown1,
      _o.Unknown2);
  }
}

public class EphbThetaT
{
  public bool Unknown1 { get; set; }
  public float Unknown2 { get; set; }

  public EphbThetaT() {
    this.Unknown1 = false;
    this.Unknown2 = 0.0f;
  }
}


static public class EphbThetaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unknown1*/, 1 /*bool*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*Unknown2*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbEpsilon : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbEpsilon GetRootAsEphbEpsilon(ByteBuffer _bb) { return GetRootAsEphbEpsilon(_bb, new EphbEpsilon()); }
  public static EphbEpsilon GetRootAsEphbEpsilon(ByteBuffer _bb, EphbEpsilon obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbEpsilon __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Unknown1 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown2 { get { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public ushort Unknown3 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public float Unknown4 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Unknown5 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon> CreateEphbEpsilon(FlatBufferBuilder builder,
      ushort unknown1 = 0,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      ushort unknown3 = 0,
      float unknown4 = 0.0f,
      float unknown5 = 0.0f) {
    builder.StartTable(5);
    EphbEpsilon.AddUnknown5(builder, unknown5);
    EphbEpsilon.AddUnknown4(builder, unknown4);
    EphbEpsilon.AddUnknown2(builder, unknown2Offset);
    EphbEpsilon.AddUnknown3(builder, unknown3);
    EphbEpsilon.AddUnknown1(builder, unknown1);
    return EphbEpsilon.EndEphbEpsilon(builder);
  }

  public static void StartEphbEpsilon(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddUnknown1(FlatBufferBuilder builder, ushort unknown1) { builder.AddUshort(0, unknown1, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset) { builder.AddOffset(1, unknown2Offset.Value, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, ushort unknown3) { builder.AddUshort(2, unknown3, 0); }
  public static void AddUnknown4(FlatBufferBuilder builder, float unknown4) { builder.AddFloat(3, unknown4, 0.0f); }
  public static void AddUnknown5(FlatBufferBuilder builder, float unknown5) { builder.AddFloat(4, unknown5, 0.0f); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon> EndEphbEpsilon(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>(o);
  }
  public EphbEpsilonT UnPack() {
    var _o = new EphbEpsilonT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbEpsilonT _o) {
    _o.Unknown1 = this.Unknown1;
    _o.Unknown2 = this.Unknown2.HasValue ? this.Unknown2.Value.UnPack() : null;
    _o.Unknown3 = this.Unknown3;
    _o.Unknown4 = this.Unknown4;
    _o.Unknown5 = this.Unknown5;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon> Pack(FlatBufferBuilder builder, EphbEpsilonT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>);
    var _unknown2 = _o.Unknown2 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown2);
    return CreateEphbEpsilon(
      builder,
      _o.Unknown1,
      _unknown2,
      _o.Unknown3,
      _o.Unknown4,
      _o.Unknown5);
  }
}

public class EphbEpsilonT
{
  public ushort Unknown1 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown2 { get; set; }
  public ushort Unknown3 { get; set; }
  public float Unknown4 { get; set; }
  public float Unknown5 { get; set; }

  public EphbEpsilonT() {
    this.Unknown1 = 0;
    this.Unknown2 = null;
    this.Unknown3 = 0;
    this.Unknown4 = 0.0f;
    this.Unknown5 = 0.0f;
  }
}


static public class EphbEpsilonVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unknown1*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTable(tablePos, 6 /*Unknown2*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*Unknown3*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*Unknown4*/, 4 /*float*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Unknown5*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbZeta : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbZeta GetRootAsEphbZeta(ByteBuffer _bb) { return GetRootAsEphbZeta(_bb, new EphbZeta()); }
  public static EphbZeta GetRootAsEphbZeta(ByteBuffer _bb, EphbZeta obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbZeta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown1 { get { int o = __p.__offset(4); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public float Unknown2 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta> CreateEphbZeta(FlatBufferBuilder builder,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      float unknown2 = 0.0f) {
    builder.StartTable(2);
    EphbZeta.AddUnknown2(builder, unknown2);
    EphbZeta.AddUnknown1(builder, unknown1Offset);
    return EphbZeta.EndEphbZeta(builder);
  }

  public static void StartEphbZeta(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddUnknown1(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset) { builder.AddOffset(0, unknown1Offset.Value, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, float unknown2) { builder.AddFloat(1, unknown2, 0.0f); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta> EndEphbZeta(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta>(o);
  }
  public EphbZetaT UnPack() {
    var _o = new EphbZetaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbZetaT _o) {
    _o.Unknown1 = this.Unknown1.HasValue ? this.Unknown1.Value.UnPack() : null;
    _o.Unknown2 = this.Unknown2;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta> Pack(FlatBufferBuilder builder, EphbZetaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta>);
    var _unknown1 = _o.Unknown1 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown1);
    return CreateEphbZeta(
      builder,
      _unknown1,
      _o.Unknown2);
  }
}

public class EphbZetaT
{
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown1 { get; set; }
  public float Unknown2 { get; set; }

  public EphbZetaT() {
    this.Unknown1 = null;
    this.Unknown2 = 0.0f;
  }
}


static public class EphbZetaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Unknown1*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyField(tablePos, 6 /*Unknown2*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbEta : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbEta GetRootAsEphbEta(ByteBuffer _bb) { return GetRootAsEphbEta(_bb, new EphbEta()); }
  public static EphbEta GetRootAsEphbEta(ByteBuffer _bb, EphbEta obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbEta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Unknown1 { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort Unknown2 { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort Unknown3 { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public ushort Unknown4 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEta> CreateEphbEta(FlatBufferBuilder builder,
      ushort unknown1 = 0,
      ushort unknown2 = 0,
      ushort unknown3 = 0,
      ushort unknown4 = 0) {
    builder.StartTable(4);
    EphbEta.AddUnknown4(builder, unknown4);
    EphbEta.AddUnknown3(builder, unknown3);
    EphbEta.AddUnknown2(builder, unknown2);
    EphbEta.AddUnknown1(builder, unknown1);
    return EphbEta.EndEphbEta(builder);
  }

  public static void StartEphbEta(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddUnknown1(FlatBufferBuilder builder, ushort unknown1) { builder.AddUshort(0, unknown1, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, ushort unknown2) { builder.AddUshort(1, unknown2, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, ushort unknown3) { builder.AddUshort(2, unknown3, 0); }
  public static void AddUnknown4(FlatBufferBuilder builder, ushort unknown4) { builder.AddUshort(3, unknown4, 0); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEta> EndEphbEta(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbEta>(o);
  }
  public EphbEtaT UnPack() {
    var _o = new EphbEtaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbEtaT _o) {
    _o.Unknown1 = this.Unknown1;
    _o.Unknown2 = this.Unknown2;
    _o.Unknown3 = this.Unknown3;
    _o.Unknown4 = this.Unknown4;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbEta> Pack(FlatBufferBuilder builder, EphbEtaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbEta>);
    return CreateEphbEta(
      builder,
      _o.Unknown1,
      _o.Unknown2,
      _o.Unknown3,
      _o.Unknown4);
  }
}

public class EphbEtaT
{
  public ushort Unknown1 { get; set; }
  public ushort Unknown2 { get; set; }
  public ushort Unknown3 { get; set; }
  public ushort Unknown4 { get; set; }

  public EphbEtaT() {
    this.Unknown1 = 0;
    this.Unknown2 = 0;
    this.Unknown3 = 0;
    this.Unknown4 = 0;
  }
}


static public class EphbEtaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Unknown1*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 6 /*Unknown2*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 8 /*Unknown3*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*Unknown4*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbIota : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbIota GetRootAsEphbIota(ByteBuffer _bb) { return GetRootAsEphbIota(_bb, new EphbIota()); }
  public static EphbIota GetRootAsEphbIota(ByteBuffer _bb, EphbIota obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbIota __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown1 { get { int o = __p.__offset(4); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown2 { get { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown3 { get { int o = __p.__offset(8); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public float Unknown4 { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbIota> CreateEphbIota(FlatBufferBuilder builder,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown3Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      float unknown4 = 0.0f) {
    builder.StartTable(4);
    EphbIota.AddUnknown4(builder, unknown4);
    EphbIota.AddUnknown3(builder, unknown3Offset);
    EphbIota.AddUnknown2(builder, unknown2Offset);
    EphbIota.AddUnknown1(builder, unknown1Offset);
    return EphbIota.EndEphbIota(builder);
  }

  public static void StartEphbIota(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddUnknown1(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset) { builder.AddOffset(0, unknown1Offset.Value, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset) { builder.AddOffset(1, unknown2Offset.Value, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown3Offset) { builder.AddOffset(2, unknown3Offset.Value, 0); }
  public static void AddUnknown4(FlatBufferBuilder builder, float unknown4) { builder.AddFloat(3, unknown4, 0.0f); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbIota> EndEphbIota(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbIota>(o);
  }
  public EphbIotaT UnPack() {
    var _o = new EphbIotaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbIotaT _o) {
    _o.Unknown1 = this.Unknown1.HasValue ? this.Unknown1.Value.UnPack() : null;
    _o.Unknown2 = this.Unknown2.HasValue ? this.Unknown2.Value.UnPack() : null;
    _o.Unknown3 = this.Unknown3.HasValue ? this.Unknown3.Value.UnPack() : null;
    _o.Unknown4 = this.Unknown4;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbIota> Pack(FlatBufferBuilder builder, EphbIotaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbIota>);
    var _unknown1 = _o.Unknown1 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown1);
    var _unknown2 = _o.Unknown2 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown2);
    var _unknown3 = _o.Unknown3 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown3);
    return CreateEphbIota(
      builder,
      _unknown1,
      _unknown2,
      _unknown3,
      _o.Unknown4);
  }
}

public class EphbIotaT
{
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown1 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown2 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown3 { get; set; }
  public float Unknown4 { get; set; }

  public EphbIotaT() {
    this.Unknown1 = null;
    this.Unknown2 = null;
    this.Unknown3 = null;
    this.Unknown4 = 0.0f;
  }
}


static public class EphbIotaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Unknown1*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 6 /*Unknown2*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Unknown3*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*Unknown4*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbGamma : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbGamma GetRootAsEphbGamma(ByteBuffer _bb) { return GetRootAsEphbGamma(_bb, new EphbGamma()); }
  public static EphbGamma GetRootAsEphbGamma(ByteBuffer _bb, EphbGamma obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbGamma __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Bone { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public VFXEditor.Flatbuffer.Ephb.EphbIota? Iota { get { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbIota?)(new VFXEditor.Flatbuffer.Ephb.EphbIota()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown1 { get { int o = __p.__offset(8); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown2 { get { int o = __p.__offset(10); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public float Unknown3 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public VFXEditor.Flatbuffer.Ephb.EphbTheta? Theta { get { int o = __p.__offset(14); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbTheta?)(new VFXEditor.Flatbuffer.Ephb.EphbTheta()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbDelta? Delta { get { int o = __p.__offset(16); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbDelta?)(new VFXEditor.Flatbuffer.Ephb.EphbDelta()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma> CreateEphbGamma(FlatBufferBuilder builder,
      uint bone = 0,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbIota> iotaOffset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbIota>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      float unknown3 = 0.0f,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta> thetaOffset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta> deltaOffset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta>)) {
    builder.StartTable(7);
    EphbGamma.AddDelta(builder, deltaOffset);
    EphbGamma.AddTheta(builder, thetaOffset);
    EphbGamma.AddUnknown3(builder, unknown3);
    EphbGamma.AddUnknown2(builder, unknown2Offset);
    EphbGamma.AddUnknown1(builder, unknown1Offset);
    EphbGamma.AddIota(builder, iotaOffset);
    EphbGamma.AddBone(builder, bone);
    return EphbGamma.EndEphbGamma(builder);
  }

  public static void StartEphbGamma(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddBone(FlatBufferBuilder builder, uint bone) { builder.AddUint(0, bone, 0); }
  public static void AddIota(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbIota> iotaOffset) { builder.AddOffset(1, iotaOffset.Value, 0); }
  public static void AddUnknown1(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset) { builder.AddOffset(2, unknown1Offset.Value, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset) { builder.AddOffset(3, unknown2Offset.Value, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, float unknown3) { builder.AddFloat(4, unknown3, 0.0f); }
  public static void AddTheta(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta> thetaOffset) { builder.AddOffset(5, thetaOffset.Value, 0); }
  public static void AddDelta(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta> deltaOffset) { builder.AddOffset(6, deltaOffset.Value, 0); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma> EndEphbGamma(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>(o);
  }
  public EphbGammaT UnPack() {
    var _o = new EphbGammaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbGammaT _o) {
    _o.Bone = this.Bone;
    _o.Iota = this.Iota.HasValue ? this.Iota.Value.UnPack() : null;
    _o.Unknown1 = this.Unknown1.HasValue ? this.Unknown1.Value.UnPack() : null;
    _o.Unknown2 = this.Unknown2.HasValue ? this.Unknown2.Value.UnPack() : null;
    _o.Unknown3 = this.Unknown3;
    _o.Theta = this.Theta.HasValue ? this.Theta.Value.UnPack() : null;
    _o.Delta = this.Delta.HasValue ? this.Delta.Value.UnPack() : null;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma> Pack(FlatBufferBuilder builder, EphbGammaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>);
    var _iota = _o.Iota == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbIota>) : VFXEditor.Flatbuffer.Ephb.EphbIota.Pack(builder, _o.Iota);
    var _unknown1 = _o.Unknown1 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown1);
    var _unknown2 = _o.Unknown2 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown2);
    var _theta = _o.Theta == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta>) : VFXEditor.Flatbuffer.Ephb.EphbTheta.Pack(builder, _o.Theta);
    var _delta = _o.Delta == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta>) : VFXEditor.Flatbuffer.Ephb.EphbDelta.Pack(builder, _o.Delta);
    return CreateEphbGamma(
      builder,
      _o.Bone,
      _iota,
      _unknown1,
      _unknown2,
      _o.Unknown3,
      _theta,
      _delta);
  }
}

public class EphbGammaT
{
  public uint Bone { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbIotaT Iota { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown1 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown2 { get; set; }
  public float Unknown3 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbThetaT Theta { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbDeltaT Delta { get; set; }

  public EphbGammaT() {
    this.Bone = 0;
    this.Iota = null;
    this.Unknown1 = null;
    this.Unknown2 = null;
    this.Unknown3 = 0.0f;
    this.Theta = null;
    this.Delta = null;
  }
}


static public class EphbGammaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Bone*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*Iota*/, VFXEditor.Flatbuffer.Ephb.EphbIotaVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Unknown1*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 10 /*Unknown2*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyField(tablePos, 12 /*Unknown3*/, 4 /*float*/, 4, false)
      && verifier.VerifyTable(tablePos, 14 /*Theta*/, VFXEditor.Flatbuffer.Ephb.EphbThetaVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 16 /*Delta*/, VFXEditor.Flatbuffer.Ephb.EphbDeltaVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbBeta : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbBeta GetRootAsEphbBeta(ByteBuffer _bb) { return GetRootAsEphbBeta(_bb, new EphbBeta()); }
  public static EphbBeta GetRootAsEphbBeta(ByteBuffer _bb, EphbBeta obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbBeta __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public VFXEditor.Flatbuffer.Ephb.EphbGamma? Gamma(int j) { int o = __p.__offset(4); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbGamma?)(new VFXEditor.Flatbuffer.Ephb.EphbGamma()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int GammaLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta> CreateEphbBeta(FlatBufferBuilder builder,
      VectorOffset gammaOffset = default(VectorOffset)) {
    builder.StartTable(1);
    EphbBeta.AddGamma(builder, gammaOffset);
    return EphbBeta.EndEphbBeta(builder);
  }

  public static void StartEphbBeta(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddGamma(FlatBufferBuilder builder, VectorOffset gammaOffset) { builder.AddOffset(0, gammaOffset.Value, 0); }
  public static VectorOffset CreateGammaVector(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateGammaVectorBlock(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGammaVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGammaVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartGammaVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta> EndEphbBeta(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>(o);
  }
  public EphbBetaT UnPack() {
    var _o = new EphbBetaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbBetaT _o) {
    _o.Gamma = new List<VFXEditor.Flatbuffer.Ephb.EphbGammaT>();
    for (var _j = 0; _j < this.GammaLength; ++_j) {_o.Gamma.Add(this.Gamma(_j).HasValue ? this.Gamma(_j).Value.UnPack() : null);}
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta> Pack(FlatBufferBuilder builder, EphbBetaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>);
    var _gamma = default(VectorOffset);
    if (_o.Gamma != null) {
      var __gamma = new Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>[_o.Gamma.Count];
      for (var _j = 0; _j < __gamma.Length; ++_j) { __gamma[_j] = VFXEditor.Flatbuffer.Ephb.EphbGamma.Pack(builder, _o.Gamma[_j]); }
      _gamma = CreateGammaVector(builder, __gamma);
    }
    return CreateEphbBeta(
      builder,
      _gamma);
  }
}

public class EphbBetaT
{
  public List<VFXEditor.Flatbuffer.Ephb.EphbGammaT> Gamma { get; set; }

  public EphbBetaT() {
    this.Gamma = null;
  }
}


static public class EphbBetaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Gamma*/, VFXEditor.Flatbuffer.Ephb.EphbGammaVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbUnknownT : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbUnknownT GetRootAsEphbUnknownT(ByteBuffer _bb) { return GetRootAsEphbUnknownT(_bb, new EphbUnknownT()); }
  public static EphbUnknownT GetRootAsEphbUnknownT(ByteBuffer _bb, EphbUnknownT obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbUnknownT __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartEphbUnknownT(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> EndEphbUnknownT(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>(o);
  }
  public EphbUnknownTT UnPack() {
    var _o = new EphbUnknownTT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbUnknownTT _o) {
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> Pack(FlatBufferBuilder builder, EphbUnknownTT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>);
    StartEphbUnknownT(builder);
    return EndEphbUnknownT(builder);
  }
}

public class EphbUnknownTT
{

  public EphbUnknownTT() {
  }
}


static public class EphbUnknownTVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbAlpha : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbAlpha GetRootAsEphbAlpha(ByteBuffer _bb) { return GetRootAsEphbAlpha(_bb, new EphbAlpha()); }
  public static EphbAlpha GetRootAsEphbAlpha(ByteBuffer _bb, EphbAlpha obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbAlpha __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public VFXEditor.Flatbuffer.Ephb.EphbBeta? Beta(int j) { int o = __p.__offset(4); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbBeta?)(new VFXEditor.Flatbuffer.Ephb.EphbBeta()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BetaLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public VFXEditor.Flatbuffer.Ephb.EphbEta? Eta(int j) { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbEta?)(new VFXEditor.Flatbuffer.Ephb.EphbEta()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EtaLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public VFXEditor.Flatbuffer.Ephb.EphbEpsilon? Epsilon(int j) { int o = __p.__offset(8); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbEpsilon?)(new VFXEditor.Flatbuffer.Ephb.EphbEpsilon()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EpsilonLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public bool Unknown1 { get { int o = __p.__offset(10); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public VFXEditor.Flatbuffer.Ephb.EphbZeta? Zeta { get { int o = __p.__offset(12); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbZeta?)(new VFXEditor.Flatbuffer.Ephb.EphbZeta()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha> CreateEphbAlpha(FlatBufferBuilder builder,
      VectorOffset betaOffset = default(VectorOffset),
      VectorOffset etaOffset = default(VectorOffset),
      VectorOffset epsilonOffset = default(VectorOffset),
      bool unknown1 = false,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta> zetaOffset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta>)) {
    builder.StartTable(5);
    EphbAlpha.AddZeta(builder, zetaOffset);
    EphbAlpha.AddEpsilon(builder, epsilonOffset);
    EphbAlpha.AddEta(builder, etaOffset);
    EphbAlpha.AddBeta(builder, betaOffset);
    EphbAlpha.AddUnknown1(builder, unknown1);
    return EphbAlpha.EndEphbAlpha(builder);
  }

  public static void StartEphbAlpha(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddBeta(FlatBufferBuilder builder, VectorOffset betaOffset) { builder.AddOffset(0, betaOffset.Value, 0); }
  public static VectorOffset CreateBetaVector(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBetaVectorBlock(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBetaVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBetaVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBetaVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEta(FlatBufferBuilder builder, VectorOffset etaOffset) { builder.AddOffset(1, etaOffset.Value, 0); }
  public static VectorOffset CreateEtaVector(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbEta>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEtaVectorBlock(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbEta>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEtaVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<VFXEditor.Flatbuffer.Ephb.EphbEta>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEtaVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<VFXEditor.Flatbuffer.Ephb.EphbEta>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEtaVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddEpsilon(FlatBufferBuilder builder, VectorOffset epsilonOffset) { builder.AddOffset(2, epsilonOffset.Value, 0); }
  public static VectorOffset CreateEpsilonVector(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEpsilonVectorBlock(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEpsilonVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEpsilonVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEpsilonVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddUnknown1(FlatBufferBuilder builder, bool unknown1) { builder.AddBool(3, unknown1, false); }
  public static void AddZeta(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta> zetaOffset) { builder.AddOffset(4, zetaOffset.Value, 0); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha> EndEphbAlpha(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha>(o);
  }
  public EphbAlphaT UnPack() {
    var _o = new EphbAlphaT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbAlphaT _o) {
    _o.Beta = new List<VFXEditor.Flatbuffer.Ephb.EphbBetaT>();
    for (var _j = 0; _j < this.BetaLength; ++_j) {_o.Beta.Add(this.Beta(_j).HasValue ? this.Beta(_j).Value.UnPack() : null);}
    _o.Eta = new List<VFXEditor.Flatbuffer.Ephb.EphbEtaT>();
    for (var _j = 0; _j < this.EtaLength; ++_j) {_o.Eta.Add(this.Eta(_j).HasValue ? this.Eta(_j).Value.UnPack() : null);}
    _o.Epsilon = new List<VFXEditor.Flatbuffer.Ephb.EphbEpsilonT>();
    for (var _j = 0; _j < this.EpsilonLength; ++_j) {_o.Epsilon.Add(this.Epsilon(_j).HasValue ? this.Epsilon(_j).Value.UnPack() : null);}
    _o.Unknown1 = this.Unknown1;
    _o.Zeta = this.Zeta.HasValue ? this.Zeta.Value.UnPack() : null;
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha> Pack(FlatBufferBuilder builder, EphbAlphaT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha>);
    var _beta = default(VectorOffset);
    if (_o.Beta != null) {
      var __beta = new Offset<VFXEditor.Flatbuffer.Ephb.EphbBeta>[_o.Beta.Count];
      for (var _j = 0; _j < __beta.Length; ++_j) { __beta[_j] = VFXEditor.Flatbuffer.Ephb.EphbBeta.Pack(builder, _o.Beta[_j]); }
      _beta = CreateBetaVector(builder, __beta);
    }
    var _eta = default(VectorOffset);
    if (_o.Eta != null) {
      var __eta = new Offset<VFXEditor.Flatbuffer.Ephb.EphbEta>[_o.Eta.Count];
      for (var _j = 0; _j < __eta.Length; ++_j) { __eta[_j] = VFXEditor.Flatbuffer.Ephb.EphbEta.Pack(builder, _o.Eta[_j]); }
      _eta = CreateEtaVector(builder, __eta);
    }
    var _epsilon = default(VectorOffset);
    if (_o.Epsilon != null) {
      var __epsilon = new Offset<VFXEditor.Flatbuffer.Ephb.EphbEpsilon>[_o.Epsilon.Count];
      for (var _j = 0; _j < __epsilon.Length; ++_j) { __epsilon[_j] = VFXEditor.Flatbuffer.Ephb.EphbEpsilon.Pack(builder, _o.Epsilon[_j]); }
      _epsilon = CreateEpsilonVector(builder, __epsilon);
    }
    var _zeta = _o.Zeta == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbZeta>) : VFXEditor.Flatbuffer.Ephb.EphbZeta.Pack(builder, _o.Zeta);
    return CreateEphbAlpha(
      builder,
      _beta,
      _eta,
      _epsilon,
      _o.Unknown1,
      _zeta);
  }
}

public class EphbAlphaT
{
  public List<VFXEditor.Flatbuffer.Ephb.EphbBetaT> Beta { get; set; }
  public List<VFXEditor.Flatbuffer.Ephb.EphbEtaT> Eta { get; set; }
  public List<VFXEditor.Flatbuffer.Ephb.EphbEpsilonT> Epsilon { get; set; }
  public bool Unknown1 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbZetaT Zeta { get; set; }

  public EphbAlphaT() {
    this.Beta = null;
    this.Eta = null;
    this.Epsilon = null;
    this.Unknown1 = false;
    this.Zeta = null;
  }
}


static public class EphbAlphaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Beta*/, VFXEditor.Flatbuffer.Ephb.EphbBetaVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Eta*/, VFXEditor.Flatbuffer.Ephb.EphbEtaVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Epsilon*/, VFXEditor.Flatbuffer.Ephb.EphbEpsilonVerify.Verify, false)
      && verifier.VerifyField(tablePos, 10 /*Unknown1*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTable(tablePos, 12 /*Zeta*/, VFXEditor.Flatbuffer.Ephb.EphbZetaVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EphbTable : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EphbTable GetRootAsEphbTable(ByteBuffer _bb) { return GetRootAsEphbTable(_bb, new EphbTable()); }
  public static EphbTable GetRootAsEphbTable(ByteBuffer _bb, EphbTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool EphbTableBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "EPHB"); }
  public static bool VerifyEphbTable(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("EPHB", false, EphbTableVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown1 { get { int o = __p.__offset(4); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown2 { get { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbAlpha? Alpha(int j) { int o = __p.__offset(8); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbAlpha?)(new VFXEditor.Flatbuffer.Ephb.EphbAlpha()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int AlphaLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbTable> CreateEphbTable(FlatBufferBuilder builder,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      VectorOffset alphaOffset = default(VectorOffset)) {
    builder.StartTable(3);
    EphbTable.AddAlpha(builder, alphaOffset);
    EphbTable.AddUnknown2(builder, unknown2Offset);
    EphbTable.AddUnknown1(builder, unknown1Offset);
    return EphbTable.EndEphbTable(builder);
  }

  public static void StartEphbTable(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddUnknown1(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset) { builder.AddOffset(0, unknown1Offset.Value, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset) { builder.AddOffset(1, unknown2Offset.Value, 0); }
  public static void AddAlpha(FlatBufferBuilder builder, VectorOffset alphaOffset) { builder.AddOffset(2, alphaOffset.Value, 0); }
  public static VectorOffset CreateAlphaVector(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateAlphaVectorBlock(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAlphaVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAlphaVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAlphaVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbTable> EndEphbTable(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbTable>(o);
  }
  public static void FinishEphbTableBuffer(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbTable> offset) { builder.Finish(offset.Value, "EPHB"); }
  public static void FinishSizePrefixedEphbTableBuffer(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbTable> offset) { builder.FinishSizePrefixed(offset.Value, "EPHB"); }
  public EphbTableT UnPack() {
    var _o = new EphbTableT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EphbTableT _o) {
    _o.Unknown1 = this.Unknown1.HasValue ? this.Unknown1.Value.UnPack() : null;
    _o.Unknown2 = this.Unknown2.HasValue ? this.Unknown2.Value.UnPack() : null;
    _o.Alpha = new List<VFXEditor.Flatbuffer.Ephb.EphbAlphaT>();
    for (var _j = 0; _j < this.AlphaLength; ++_j) {_o.Alpha.Add(this.Alpha(_j).HasValue ? this.Alpha(_j).Value.UnPack() : null);}
  }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbTable> Pack(FlatBufferBuilder builder, EphbTableT _o) {
    if (_o == null) return default(Offset<VFXEditor.Flatbuffer.Ephb.EphbTable>);
    var _unknown1 = _o.Unknown1 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown1);
    var _unknown2 = _o.Unknown2 == null ? default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>) : VFXEditor.Flatbuffer.Ephb.EphbUnknownT.Pack(builder, _o.Unknown2);
    var _alpha = default(VectorOffset);
    if (_o.Alpha != null) {
      var __alpha = new Offset<VFXEditor.Flatbuffer.Ephb.EphbAlpha>[_o.Alpha.Count];
      for (var _j = 0; _j < __alpha.Length; ++_j) { __alpha[_j] = VFXEditor.Flatbuffer.Ephb.EphbAlpha.Pack(builder, _o.Alpha[_j]); }
      _alpha = CreateAlphaVector(builder, __alpha);
    }
    return CreateEphbTable(
      builder,
      _unknown1,
      _unknown2,
      _alpha);
  }
}

public class EphbTableT
{
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown1 { get; set; }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownTT Unknown2 { get; set; }
  public List<VFXEditor.Flatbuffer.Ephb.EphbAlphaT> Alpha { get; set; }

  public EphbTableT() {
    this.Unknown1 = null;
    this.Unknown2 = null;
    this.Alpha = null;
  }
  public static EphbTableT DeserializeFromBinary(byte[] fbBuffer) {
    return EphbTable.GetRootAsEphbTable(new ByteBuffer(fbBuffer)).UnPack();
  }
  public byte[] SerializeToBinary() {
    var fbb = new FlatBufferBuilder(0x10000);
    EphbTable.FinishEphbTableBuffer(fbb, EphbTable.Pack(fbb, this));
    return fbb.DataBuffer.ToSizedArray();
  }
}


static public class EphbTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTable(tablePos, 4 /*Unknown1*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 6 /*Unknown2*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Alpha*/, VFXEditor.Flatbuffer.Ephb.EphbAlphaVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
