// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace VFXEditor.Flatbuffer.Ephb
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EphbGamma : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EphbGamma GetRootAsEphbGamma(ByteBuffer _bb) { return GetRootAsEphbGamma(_bb, new EphbGamma()); }
  public static EphbGamma GetRootAsEphbGamma(ByteBuffer _bb, EphbGamma obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EphbGamma __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Bone { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown1 { get { int o = __p.__offset(6); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown2 { get { int o = __p.__offset(8); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbUnknownT? Unknown3 { get { int o = __p.__offset(10); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbUnknownT?)(new VFXEditor.Flatbuffer.Ephb.EphbUnknownT()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public float Unknown4 { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public VFXEditor.Flatbuffer.Ephb.EphbTheta? Theta { get { int o = __p.__offset(14); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbTheta?)(new VFXEditor.Flatbuffer.Ephb.EphbTheta()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public VFXEditor.Flatbuffer.Ephb.EphbDelta? Delta { get { int o = __p.__offset(16); return o != 0 ? (VFXEditor.Flatbuffer.Ephb.EphbDelta?)(new VFXEditor.Flatbuffer.Ephb.EphbDelta()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma> CreateEphbGamma(FlatBufferBuilder builder,
      uint bone = 0,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown3Offset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT>),
      float unknown4 = 0.0f,
      Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta> thetaOffset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta>),
      Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta> deltaOffset = default(Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta>)) {
    builder.StartTable(7);
    EphbGamma.AddDelta(builder, deltaOffset);
    EphbGamma.AddTheta(builder, thetaOffset);
    EphbGamma.AddUnknown4(builder, unknown4);
    EphbGamma.AddUnknown3(builder, unknown3Offset);
    EphbGamma.AddUnknown2(builder, unknown2Offset);
    EphbGamma.AddUnknown1(builder, unknown1Offset);
    EphbGamma.AddBone(builder, bone);
    return EphbGamma.EndEphbGamma(builder);
  }

  public static void StartEphbGamma(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddBone(FlatBufferBuilder builder, uint bone) { builder.AddUint(0, bone, 0); }
  public static void AddUnknown1(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown1Offset) { builder.AddOffset(1, unknown1Offset.Value, 0); }
  public static void AddUnknown2(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown2Offset) { builder.AddOffset(2, unknown2Offset.Value, 0); }
  public static void AddUnknown3(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbUnknownT> unknown3Offset) { builder.AddOffset(3, unknown3Offset.Value, 0); }
  public static void AddUnknown4(FlatBufferBuilder builder, float unknown4) { builder.AddFloat(4, unknown4, 0.0f); }
  public static void AddTheta(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbTheta> thetaOffset) { builder.AddOffset(5, thetaOffset.Value, 0); }
  public static void AddDelta(FlatBufferBuilder builder, Offset<VFXEditor.Flatbuffer.Ephb.EphbDelta> deltaOffset) { builder.AddOffset(6, deltaOffset.Value, 0); }
  public static Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma> EndEphbGamma(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<VFXEditor.Flatbuffer.Ephb.EphbGamma>(o);
  }
}


static public class EphbGammaVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Bone*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*Unknown1*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 8 /*Unknown2*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 10 /*Unknown3*/, VFXEditor.Flatbuffer.Ephb.EphbUnknownTVerify.Verify, false)
      && verifier.VerifyField(tablePos, 12 /*Unknown4*/, 4 /*float*/, 4, false)
      && verifier.VerifyTable(tablePos, 14 /*Theta*/, VFXEditor.Flatbuffer.Ephb.EphbThetaVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 16 /*Delta*/, VFXEditor.Flatbuffer.Ephb.EphbDeltaVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
