using System.Collections.Generic;

namespace VfxEditor.AtchFormat.Utils {

    public class AtchUtils {
        public static readonly Dictionary<string, string> WeaponNames = new() {
            { "2ax", "Greataxe" },
            { "2bk", "Book" },
            { "2bw", "Bow" },
            { "2ff", "Nouliths" },
            { "2gb", "Gunblade" },
            { "2gl", "Globe" },
            { "2gn", "Gun" },
            { "2km", "Scythe" },
            { "2kt", "Katana" },
            { "2rp", "Rapier" },
            { "2sp", "Spear" },
            { "2st", "Greatstaff" },
            { "2sw", "Greatsword" },
            { "aai", "Alchemist" },
            { "aal", "Alchemist" },
            { "aar", "Armorer" },
            { "abl", "Armorer" },
            { "aco", "Culinarian" },
            { "agl", "Goldsmith" },
            { "ali", "Alchemist" },
            { "alm", "Alchemist" },
            { "alt", "Leatherworker" },
            { "ase", "Weaver" },
            // { "atr", "" },
            { "avt", "Reaper Avatar" },
            { "awo", "Carpenter" },
            { "bag", "Machinist Bag" },
            { "bl2", "Viper Blade OffHand" },
            { "bld", "Viper Blade" },
            // { "bll", "" },
            { "brs", "Pictomancer Brush" },
            { "chk", "Chakram" },
            // { "clb", "" },
            { "clg", "Glove" },
            // { "cls", "" }, // Linked to axes
            { "clw", "Claw" },
            // { "col", "" },
            // { "cor", "" },
            // { "cos", "" },
            { "crd", "Astrologian Deck" },
            { "crr", "Astrologian Card" }, // Also pomanders
            // { "crt", "" },
            { "csl", "Carpenter" },
            { "csr", "Carpenter" },
            { "dgr", "Dagger" },
            { "drm", "Drum" },
            { "ebz", "Bazooka" },
            // { "egp", "" },
            // { "elg", "" },
            { "fch", "Fisher Chair" },
            // { "fdr", "" },
            { "fha", "Fisher Gig" },
            // { "fl2", "Harp" },
            { "flt", "Flute" },
            { "frg", "Ninja Frog" },
            { "fry", "Leatherworker/Culinarian" },
            { "fsh", "Fisher" },
            { "fsw", "Fist Weapons" },
            { "fud", "Paint Brush" },
            // { "gdb", "" },
            // A bunch of Event items use the same ones
            { "gdh", "Event Bottle" }, //pc_contentaction/holywater
            { "gdl", "Event Left Hand" }, //pc_contentsaction/pc_cnt018
            { "gdr", "Event Right Hand" }, //pc_contentsaction/lantern
            { "gdt", "Event Rod" }, //pc_contentsaction/etherex
            // { "gdw", "" },
            { "gsl", "Machinist Deployable" },
            // { "gsr", "" }, // Diadem cannon?
            // { "gun", "" },
            // { "hel", "" },
            { "hmm", "Blacksmith/Armorer" },
            { "hrp", "Bard Harp" },
            { "htc", "Botanist" },
            { "ksh", "Samurai Sheath" },
            // { "let", "" },
            // { "lpr", "" }, // Linked to 1923
            { "mlt", "Goldsmith" },
            { "mmc", "Machinist FullMetal" },
            { "mrb", "Alchemist" },
            { "mrh", "Alchemist" },
            { "msg", "Machinist Shotgun" },
            { "mwp", "Machinist Cannon" },
            { "ndl", "Weaver" },
            // { "nik", "" }, // Linked to Nier pod, maybe Nikana or something
            { "njd", "Ninja Double" },
            { "nph", "Botanist" },
            { "orb", "Red Mage Focus" },
            // { "oum", "" },
            { "pen", "Arcanist Pen" },
            { "pic", "Pickaxe" },
            { "plt", "Pictomancer Palette" },
            // { "pra", "" },
            { "prf", "Leatherworker" },
            { "qvr", "Quiver" },
            // { "rap", "" },
            { "rbt", "Ninja Rabbit" },
            { "rod", "Blue Mage Rod" },
            // { "rop", "" },
            { "saw", "Carpenter" },
            // { "sht", "" },
            { "sic", "Sickle" },
            { "sld", "Shield" },
            { "stf", "Staff" },
            { "stv", "Culinarian" },
            { "swd", "Sword" },
            //{ "sxs", "" },
            { "sxs", "Pheonix Wing" },
            { "syl", "Summoned Weapon Left" },
            { "syr", "Summoned Weapon Right" },
            { "syu", "Ninja Shuriken" },
            { "syw", "Summoned Weapon Throw" },
            // { "tan", "" },
            { "tbl", "Goldsmith" },
            // { "tcs", "" },
            { "tgn", "Goldsmith" },
            { "tmb", "Weaver" },
            // { "trm", "" }, // Linked to flute
            { "trr", "Scholar Seraph (LB)" },
            // { "trw", "" }, // Linked to greatswords
            { "vln", "Bard Violin" },
            { "whl", "Weaver" },
            { "wng", "Wings" },
            { "ypd", "Nier Pod" },
            { "ytk", "Armorer" },
        };
    }
}
